# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules: 
  - line_length

# line_length:
#   warning: 120
#   ignores_function_declarations: true
#   ignores_comments: true
#   ignores_interpolated_strings: true
#   ignores_urls: true
